input_text_desired_length: 110
input_text_max_length: 170
output_folder_path: outputs
selected_theme: Default
server_name: ''
server_port: 0
server_share: false
silence_between_sentences: 250
silence_between_speakers: 500
